### ISSUE TITLE
there isn't a gitignore file shouldn't it be added.

### ISSUE THREAD

**Issue by deep-shekhar** [metakgp/mfqp#13]

**Comment by athityakumar** [comment]
@deep-shekhar - Can you elaborate on this issue - which file(s) are you referring to, for adding a `.gitignore`?

**Comment by vivekiitkgp** [comment]
@athityakumar I think he simply wants to add a `.gitignore` file that currently does not exist in the repository.

**Comment by deep-shekhar** [comment]
I guess there should be a .gitignore file for the add_node.rb file as it is a ruby code.And in general when more codes will be added we can subsequently add to the .gitignore

**Comment by athityakumar** [comment]
@deep-shekhar - Hmm - changes can also happen in these scripts like `add_node.rb`. For example, `add_node.rb` had some features added last summer. And probably, there may even be a few more additional features in the future. So, do we really need to stop tracking git changes on such scripts?

**Comment by icyflame** [comment]
The add_node.rb file is part of the repository.
