### ISSUE TITLE
Add CNAME for mfqp.metakgp.org too!

### ISSUE THREAD

**Issue by vivekiitkgp** [metakgp/mfqp#14]
I guess it makes sense to have this entry too.

**Comment by icyflame** [comment]
@vivekiitkgp Discussed this with @amrav earlier. He said that qp.metakgp.org is a good one.

**Comment by vivekiitkgp** [comment]
Yes, it's a good one. But is it not possible to add multiple CNAME entries? @icyflame

**Comment by icyflame** [comment]
@vivekiitkgp I think from DNS side we can add, but I am not sure that Github pages allows the same page to be served from two different links. ( https://help.github.com/articles/using-a-custom-domain-with-github-pages/ )

I think they allow only one external domain to serve a Github page.

**Comment by icyflame** [comment]
We can definitely add `mfqp.metakgp.org CNAME qp.metakgp.org`, that will get the functionality that you have mentioned here.

**Comment by icyflame** [comment]
There can be only one CNAME, it seems. I added the DNS record `mfqp.metakgp.org CNAME qp.metakgp.org` and it showed a 404 at that page:

![image](https://cloud.githubusercontent.com/assets/3668034/21741644/f4244f0a-d502-11e6-89a1-cd6a354d8bf6.png)

I believe that a GitHub page can be rendered only on the website which has been mentioned in the CNAME record inside the repository.

I am closing this issue. If you have found another method to show the same page at two domains, or want to implement a HTML file that will redirect people to qp.metakgp.org, you may re-open it.

**Comment by athityakumar** [comment]
@icyflame - If it's all anyway hosted on `metakgp.org` server, can't we simply have a `index.php` for the `mfqp` sub-domain that redirects to the `qp` sub-domain?
