### ISSUE TITLE
Improve front-end

### ISSUE THREAD

**Issue by athityakumar** [metakgp/mfqp#20]
The search and drop-down UI looks so much more neat on Semantic-UI. [Example](http://semantic-ui.com/modules/search.html)

**Comment by amrav** [comment]
Thanks for thinking about UI improvements, when done right, it can makes
the user experience delightful. The search box looks quite spartan and can
probably be tweaked, but why do you think a dropdown would help? Do you
think the way search results currently appear instantly isn't meeting some
requirement?

**Comment by athityakumar** [comment]
- Have a look at this [example](http://semantic-ui.com/modules/dropdown.html#search-selection) - seems more attractive to me than the existing one. 
- The current UI isn't friendly on mobiles - I once tried out `mfqp` from my mobile while I was in the class (because I had no laptop in class), and the search results just seemed like one massive paragraph, where distinguishing one paper from one another, and finding out the required paper were both difficult.

Perhaps the Semantic UI example shown above will solve the Mobile issue?

**Comment by amrav** [comment]
I agree about the UI being bad on mobile. We should use some kind of
lightweight CSS framework, not sure if it's already using Bootstrap.

I don't think I understand how a dropdown would work for mfqp. That makes
sense when you have to select one thing - but the way it currently works is
like a filter and ranker. Are you thinking of changing that?

**Comment by athityakumar** [comment]
Nope, not at all. The JS part will be of the `worker` and `fuse`. Just the UI part will be made with Semantic UI. If Semantic-UI seems heavy, we can just use the dropdown UI part of it - not the whole package.

**Comment by icyflame** [comment]
Homepage looks like this:

![screenshot_20170312-002509](https://cloud.githubusercontent.com/assets/3668034/23826011/95516c58-06ba-11e7-832c-ca8238289185.png)

Search results look like this:

![screenshot_20170312-002523](https://cloud.githubusercontent.com/assets/3668034/23826012/965512ee-06ba-11e7-8676-fbdd6d10d723.png)

This is on the Chromium based Brave browser, 1080p screen. Not sure what @athityakumar meant by

> the search results just seemed like one massive paragraph, where distinguishing one paper from one > another, and finding out the required paper were both difficult.

I feel like the present UI looks good, actually.

As an improvement, we might use Bootstrap's cards. Bootstrap is pretty good, and a list group UI separates the results in a much better manner, but some changes are still required.

![screenshot_20170312-004749](https://cloud.githubusercontent.com/assets/3668034/23826223/f09e30fc-06bd-11e7-97f5-50ec2f2d785e.png)

The code for this is [on this branch](https://github.com/icyflame/mfqp/tree/trying-new-ui-boostrap). @athityakumar have a look if you are interested.

**Comment by athityakumar** [comment]
Thanks for the suggestions, @icyflame and @amrav - I was thinking if we can add showcase the results as bootstrap cards just like [this](https://athityakumar.github.io/naarad-source/). That is, Fuzzy search + Bootstrap UI of Table / Cards.

**Comment by vivekiitkgp** [comment]
@athityakumar I see your point. Here's what I think (following from the issue on mcmp): I think that with respect to mfqp, the only problem we need to address is the visibility/appearance on the mobile devices. I find the desktop/normal UI to be highly visible, easy to use, and intuitive. Plus, it's relatively easy to understand and modify (a newcomer won't have to dig any fancy library docs). That makes me a little wary of dropdown/Semantic UI idea.

However, I'd like to see how Bootstrap UI helps us in this regard. Specially, in terms of introducing clarity and improving visibility on mobile devices.

**Comment by icyflame** [comment]
Closed in favor of #36. This issue has a very vague title.
