### ISSUE TITLE
[add_node.rb] Re-write with better code semantics

### ISSUE THREAD

**Issue by athityakumar** [metakgp/mfqp#22]
I saw a ridiculous block like 

```
if condition
   return true
else
   return false
end
```
which could just be made to `return condition`.

There are many other minor clean-ups required, that don't change the logic / execution of the program - but just for the love of good programming.

**Comment by icyflame** [comment]
@athityakumar Yeah, definitely. Actually, I would like to clean it up a bit. And after that, you can review it yourself and submit some changes that would make it even better. I was in some kind of a hurry to write it, and it turned out to be rather sloppy.

**Comment by athityakumar** [comment]
Sure. :smile:

**Comment by icyflame** [comment]
@athityakumar Improvements made in eafae6b11a. Have a look. If you can make some more improvements, please open a PR for the same. If not, you can close this issue. :smile:

**Comment by athityakumar** [comment]
Fixed with commit eafae6b11a26355d2c81aee3f1521c6b13a45998 and PR #23
