### ISSUE TITLE
Create a "search" URL parameter

### ISSUE THREAD

**Issue by icyflame** [metakgp/mfqp#27]
Inside `index.html`, parse the URL using JavaScript (or jQuery?) and fill the search bar.

Some common parameters like `qp.metakgp.org?search=...` and `qp.metakgp.org?q=...` can be supported. This will enable adding MFQP as a search engine in Chrome and Firefox.

**Comment by punit1108** [comment]
@icyflame [https://github.com/metakgp/mfqp/pull/28](url)

**Comment by punit1108** [comment]
@icyflame #29

**Comment by icyflame** [comment]
Solved in #30
