### ISSUE TITLE
Implement better UI on mobile screens

### ISSUE THREAD

**Issue by icyflame** [metakgp/mfqp#36]
The overall UI and UX should remain the same, but the visibility right now is very bad. That can be improved.

![screenshot_20171117-144350](https://user-images.githubusercontent.com/3668034/32939770-a083371c-cba6-11e7-8e45-d63adcb184e5.png)

**Comment by akhilesh-k** [comment]
We have done it! You might want to have a look.

http://akhileshkumar.me/metaqp-test
