### ISSUE TITLE
Feature Request: Add sorting by year and preference to search exact string (no fuzzy search)

### ISSUE THREAD

**Issue by djbarnwal** [metakgp/mfqp#42]
Many times I would want to see the latest papers first. Sorting the results by year can be very helpful.

As course names do no change over time (ideally) it makes sense to have exact search (in the sense that search keywords are in the title of the paper*) instead of fuzzy search sometimes which clutter the results with unwanted papers. An option can be added to switch on/off the fuzzy search.

\* Searching 'Quality Design' would match 'Quality of Design and Control'

**Comment by icyflame** [comment]
@djbarnwal Remember that papers aren't always named exactly the course code or course name. They are arbitrary. In that kind of a case (where the data we want to search in is mixed and isn't properly structured), the best we can do is Fuzzy search.

**Comment by icyflame** [comment]
Similar discussion [here](https://github.com/metakgp/mfqp/issues/32#issuecomment-297965787
