### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Ayushk4** [metakgp/mfqp#47]
In most other projects we have stuck with GNU GPL License. We can do the same with this.

**Comment by Ayushk4** [comment]
@thealphadollar Ping.

**Comment by raivivek** [comment]
Yes please go ahead and add the LICENSE file.

**Comment by berserker1** [comment]
@Ayushk4  I think we can safely close it now.

**Comment by Ayushk4** [comment]
@berserker1 Sure let #49 be merged.
