### ISSUE TITLE
Use new method for scraping papers from Library

### ISSUE THREAD

**Issue by berserker1** [metakgp/mfqp#50]
Since IITKGP Library hosted new its new website ( they copied a wiki template from somewhere most probably ). The papers are obtained from [here](http://www.library.iitkgp.ac.in/pages/SemQuestionWiki/index.php/Main_Page).

A new method has been devised and necessary PR will be sent shortly

**Comment by icyflame** [comment]
@berserker1 Oh, this is great! 👏 Do you know if this new method is being used only for newer papers or is it being used as the only system for all papers?

**Comment by berserker1** [comment]
> @berserker1 Oh, this is great!  Do you know if this new method is being used only for newer papers or is it being used as the only system for all papers?

Well, actually they have moved the whole previous database here as well as add the new ones.
Mid sems ended on 24th Sep, I think except that their data is up to date.

Also [Grapheo12](https://github.com/grapheo12) has picked up the issue, can you just assign him this and add a few labels just to make the issue complete.

**Comment by berserker1** [comment]
- We had a plan for just showing the links to the pdfs on the library website, but @thealphadollar pointed about cases when their server will be down ( I think it will be down 90% of the time it is required ), so we will again maintain our separate database.

- Since now the section of our importance [Semester Questions and Resources Wiki](www.library.iitkgp.ac.in/pages/SemQuestionWiki/index.php/Main_Page) opted a wiki style format, we thought of using [Pywikibot](https://github.com/wikimedia/pywikibot), but I think for obtaining data, we require creation of bot account, which I do not know they will allow, so we shifted to scraping instead.

**Comment by thealphadollar** [comment]
@grapheo Please look into this.

**Comment by amrav** [comment]
> *Students may contribute question paper by using smart phone scan apps.
Please email to* *samrat@library.iitkgp.ac.in <samrat@library.iitkgp.ac.in>*
.

This is great if it works, we can forward all our contributed papers here
and just mirror them once they're put up?

**Comment by amrav** [comment]
I think it's important to establish a relationship with the person first,
eg send them a few papers first and say that more will arrive, or even
better, go and talk to them in person. Easy opportunity to get someone on
our side, and maybe even understand better the functioning of the library
website.

**Comment by berserker1** [comment]
>send them a few papers first and say that more will arrive, or even
better, go and talk to them in person.

We can explain to them by stating the facts i.e very few knew about this `new domain` for hosting the question papers, we came to know cause we wanted to update mfqp.  
Metakgp has far reach and trust as among the community and if we are able to get them on our side it will also be a great benefit for them.

**Comment by grapheo12** [comment]
Should I bs4 or selenium for this?

**Comment by grapheo12** [comment]
Just found that, they refer to mfqp site for searching. Also the previous paper dump link has changed to 10.18.24.22/peqp

**Comment by grapheo12** [comment]
I built this scraping script. It uses text based search. So it can be modified easily if infuture the structure of the site changes. Please review it. Run on your machine to see the output. If it is okay I'll send a proper PR.
https://gist.github.com/grapheo12/f00e767158a806e550b6da499dd19eac

**Comment by grapheo12** [comment]
@thealphadollar ?

**Comment by thealphadollar** [comment]
LGTM! I was looking for some modification over the already present script but this one shall be equally good and maintainable. What do you say, @berserker1 ?

**Comment by grapheo12** [comment]
@thealphadollar @berserker1 Please review my PR.
