### ISSUE TITLE
Recent Searches Not Working

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/mfqp#54]
Recent searches section seems to be broken as it is not showing previous searches.

**Comment by icyflame** [comment]
@thealphadollar What do you mean not working? It works properly. Items are added to the recent searches list when you search for something and then click on a result row.

**Comment by icyflame** [comment]
:spiral_notepad: I have removed the `bug` label for now. Current description isn't a bug and there's not enough detail in the issue to understand what one should work on for this issue.

**Comment by thealphadollar** [comment]
As I search for a new query and download it's PDF file, I expect the "Recent Searches" to store it and when I open the page again, show me my past searches. This behaviour is not working as intended and it is not saving my recent searches.

The code line to look for debugging is [L49](https://github.com/metakgp/mfqp/blob/140966c6b68075ceb5303bcbaecec4903cce26ac/client.js#L49) of `client.js` as it deals with the task of adding new items to the list.

[L37](https://github.com/metakgp/mfqp/blob/140966c6b68075ceb5303bcbaecec4903cce26ac/client.js#L37) deals with the task of adding the items from the search list to the recent searches.

**Comment by icyflame** [comment]
@thealphadollar What browser are you using? Can you open your browser console and check if any errors are being printed? It's possible that this is a browser specific issue, because it works properly for me. :+1

**Comment by thealphadollar** [comment]
My apologies in the regard of not creating a detailed bug report; as end sems are going on I tried to make it quick for myself.

Anyways, I believe I've added all the relevant details in the third comment but the system and browser version.
