### ISSUE TITLE
Create Issues And Pull Request Templates

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/mfqp#56]
To remove the discrepancy between how issues and bugs are created and to enforce a standard across the same, we should have templates for Issues and PRs. This will help in a standarisation of bug reporting and patching.

Below are two resources which can be used for looking for suitable templates:

- https://github.com/stevemao/github-issue-templates
- https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

In the bug report, it is advisable to have the following fields:
- [ ] Summary
- [ ] Actual Behaviour
- [ ] Expected Behaviour
- [ ] Steps To Reproduce
- [ ] Screenshots, if applicable
- [ ] Other Relevant Information (System info, browser etc)

In the PR, it is advisable to have the following fields:
- [ ] Summary
- [ ] Details About The Changes
- [ ] Screenshots, if applicable
- [ ] Bugs Introduced By The Patch
- [ ] Reference Concerned Issues

**Comment by sahil-shubham** [comment]
Hi there, I would like to work on this issue. Is it available?

**Comment by thealphadollar** [comment]
Thanks @sahil-shubham for the initiative; the issue is open to take, please go ahead.

**Comment by sahil-shubham** [comment]
These are the initial issue and pull request template respectively:
![issue_template](https://user-images.githubusercontent.com/60931421/92016912-a2b34880-ed70-11ea-8bd7-9cea5788f0a3.png)
![pull_request_template](https://user-images.githubusercontent.com/60931421/92016934-a777fc80-ed70-11ea-9156-b520e01b4b87.png)

Let me know what you think about these.
 
I was thinking about adding separate issue templates for bug report and new feature, what do you think about it?

**Comment by thealphadollar** [comment]
@sahil-shubham They look perfect, thanks for taking the time. 

Have you heard of the principle "ask for forgiveness, not permission"? It'll make the review faster for you if you raise a PR directly and we will discuss any changes that we need in the PR itself :smile: Do you think that would be better for the process?

**Comment by sahil-shubham** [comment]
>Do you think that would be better for the process?

yes,that would be better. I would remember that from now on, thank you for guiding me.
