### ISSUE TITLE
Recent searches column: Using LocalStorage

### ISSUE THREAD

**Issue by icyflame** [metakgp/mfqp#7]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

cc @amrav @xtinct

**Comment by icyflame** [comment]
Started work on this here: https://github.com/icyflame/mfqp/tree/add-local-storage

**Comment by zorroblue** [comment]
@icyflame Can I work on this?

**Comment by icyflame** [comment]
@zorroblue Most of the work is actually done on this, just some UI improvements and a few choices to be made. Sure, you can certainly work on it. make sure to work on top of my tree, so that you don't do things all over again. (Ping me in case of any problems you might face in understanding what I've written.)

**Comment by vivekiitkgp** [comment]
Bump! @icyflame @zorroblue

**Comment by icyflame** [comment]
hey @vivekiitkgp thanks for the bump! The work is here: https://github.com/icyflame/mfqp/tree/local-storage-final

There are a few things that are still remaining on this patch are [here](https://github.com/metakgp/mfqp/pull/12#issuecomment-248917215).

> 1. Making the search terms clickable
> 2. Ensuring that we don't add the same term into the list again and again
